In [1]:
import os 
import pickle
import pandas as pd
import numpy as np
import pprint


In [2]:
from enum import IntEnum
class HandleStatus(IntEnum):
    VALID = 1
    MISSING = 2
    DISABLED = 4
    

In [3]:
pwd


'/Users/colin/Documents/AKH/NDIPolaris'

In [4]:
import ndi_polaris_04_07 as ndi

In [5]:
d = pd.read_pickle('./Measurement_J')

data d = list of frames ,each frame (one list entry) is a dictionary. 

dict keys are system_status, handles, stray_markers, time_stamps. handle is a list with the number of trackers tracked.

each handle is a dict with: 'handle', 'status', 'quaternion', 'translation', 'error', 'port_status', 'frame_number', 'tool_information', 'marker_information', 'n_markers', 'marker_out_of_volume', 'markers'

In [6]:
d[0]['handles'][0].keys()

dict_keys(['handle', 'status', 'quaternion', 'translation', 'error', 'port_status', 'frame_number', 'tool_information', 'marker_information', 'n_markers', 'marker_out_of_volume', 'markers'])

In [7]:
d[0]['handles'][0]['handle']

'01'

In [8]:
for i in range (0,5):
    print(d[0]['handles'][i]['translation'])

[  129.63951111     9.36485004 -1365.39794922]
[  -68.77826691   -10.17350483 -1532.30761719]
[   90.84767914   214.09114075 -1392.46643066]
[  -53.53369141   183.3974762  -1514.07067871]
[  -25.34035301     4.08954954 -1495.39294434]


In [9]:
n = np.empty([len(d), len(d[0]['handles']),3]) #creates an empty numppy array with the dimension of the frames and the handles with 3 dim

In [10]:
#make n a np 3 dim array with frames, handles and their koordinates
for i in range (0,len(d)):
    for j in range (0,5):
        n[i,j]=(d[i]['handles'][j]['translation'])

In [11]:
for i in range (5):
    for j in range(3):
        print(np.sqrt(np.var(n[:,i,j])))

0.0520965889494453
0.09336261096312323
0.04085651917091721
0.056782226748758276
0.1060106862659918
0.05591309552793435
0.048627851991102804
0.0954805063335245
0.03303522791470249
0.05242970567038193
0.10486300863292104
0.04743364866179441
0.05436464096775174
0.10314257602860807
0.05017094574994622


In [12]:
len(d)

10540

In [13]:
data = []

In [14]:
# Remove double Frame numbers
for i in range(len(d)):
    if i == 0:
        data.append(d[i])
    else:
        if d[i]['handles'][0]['frame_number'] != data[len(data)-1]['handles'][0]['frame_number']:
            data.append(d[i])
            
print(len(data))            
            
    

3992


In [15]:
for i in range (5):
    print(data[0]['handles'][i]['translation'])

[  129.63951111     9.36485004 -1365.39794922]
[  -68.77826691   -10.17350483 -1532.30761719]
[   90.84767914   214.09114075 -1392.46643066]
[  -53.53369141   183.3974762  -1514.07067871]
[  -25.34035301     4.08954954 -1495.39294434]


In [16]:
nd = np.empty([len(data), len(data[0]['handles']),len(data[0]['handles'])])

In [17]:
nd[0].shape

(5, 5)

In [18]:
for a in range(len(data)):
    for i in range (5):
        for j in range (5):
            x = data[a]['handles'][i]['translation']
            y = data[a]['handles'][j]['translation']
            nd[a][i,j] = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2+(x[2]-y[2])**2)

In [19]:
nd[13]

array([[  0.        , 260.01940499, 210.12173249, 293.16947045,
        202.36084371],
       [260.01940499,   0.        , 308.75733021, 195.02397865,
         58.75013281],
       [210.12173249, 308.75733021,   0.        , 191.25748473,
        261.15030893],
       [293.16947045, 195.02397865, 191.25748473,   0.        ,
        182.47229938],
       [202.36084371,  58.75013281, 261.15030893, 182.47229938,
          0.        ]])

In [20]:
nd_var=np.zeros([6,6])

In [21]:
np.sqrt(np.var(nd[:][0,1]))

117.5640159618295

In [22]:
for i in range (5):
    for j in range(5):
        if i != j:
            print(np.sqrt(np.var(nd[:,i,j])))

0.008237272166167767
0.0029180143689386028
0.007571455758311209
0.007288548610248404
0.008237272166167767
0.006028536342431129
0.0027537087616864952
0.008776439394217647
0.0029180143689386028
0.006028536342431129
0.009104193870436808
0.004821215634389656
0.007571455758311209
0.0027537087616864952
0.009104193870436808
0.003194870612111212
0.007288548610248404
0.008776439394217647
0.004821215634389656
0.003194870612111212
